"use client";

import { useEffect, useState } from "react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Empty, Loading, RangeSelect } from "@/components/dashboard-overview";

type Row = { [key: string]: string | number | null };
const colors = ["#062f5f", "#2563eb", "#60a5fa", "#f4b41a", "#16a34a", "#9333ea", "#64748b"];

export default function AnalyticsDashboard() {
  const [range, setRange] = useState("30d"); const [sources, setSources] = useState<Row[]>([]); const [locations, setLocations] = useState<Row[]>([]); const [devices, setDevices] = useState<Row[]>([]); const [campaigns, setCampaigns] = useState<Row[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); Promise.all(["sources", "locations", "devices", "campaigns"].map((endpoint) => fetch(`/api/analytics/${endpoint}?range=${range}`).then((response) => response.json()))).then(([sourceBody, locationBody, deviceBody, campaignBody]) => { setSources(sourceBody.data ?? []); setLocations(locationBody.data ?? []); setDevices(deviceBody.data ?? []); setCampaigns(campaignBody.data ?? []); }).finally(() => setLoading(false)); }, [range]);
  return <><header className="topbar"><div><p className="eyebrow">Audience intelligence</p><h1>Website analytics</h1><p className="subtitle">Understand visitor origin, technology and marketing performance.</p></div><RangeSelect value={range} onChange={setRange}/></header>{loading ? <Loading/> : <div className="analytics-grid"><Distribution title="Traffic sources" note="Unique visitors by acquisition source" rows={sources} label="source"/><Distribution title="Device categories" note="Desktop, mobile and tablet usage" rows={devices} label="device"/><RankedTable title="Top visitor countries" rows={locations} columns={["country", "visitors", "percentage"]}/><RankedTable title="UTM campaign conversions" rows={campaigns} columns={["campaign", "source", "visitors", "conversions"]}/></div>}</>;
}

function Distribution({ title, note, rows, label }: { title: string; note: string; rows: Row[]; label: string }) { const chartData = rows.map((row) => ({ name: String(row[label]), value: Number(row.visitors) })); return <article className="panel"><div className="panel-head"><div><h2>{title}</h2><p className="panel-note">{note}</p></div></div>{rows.length ? <div className="distribution"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="value" nameKey="name" innerRadius={56} outerRadius={82} paddingAngle={2}>{chartData.map((_, index) => <Cell key={index} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="legend">{rows.slice(0, 7).map((row, index) => <div key={String(row[label])}><span style={{ background: colors[index % colors.length] }}/><strong>{String(row[label])}</strong><em>{String(row.percentage)}%</em></div>)}</div></div> : <Empty text="No data for this period."/>}</article>; }
function RankedTable({ title, rows, columns }: { title: string; rows: Row[]; columns: string[] }) { return <article className="panel"><div className="panel-head"><div><h2>{title}</h2><p className="panel-note">Based on the selected reporting period</p></div></div>{rows.length ? <div className="table-scroll compact"><table><thead><tr>{columns.map((column) => <th key={column}>{column.replace(/([A-Z])/g, " $1")}</th>)}</tr></thead><tbody>{rows.slice(0, 10).map((row, index) => <tr key={index}>{columns.map((column) => <td key={column}>{String(row[column] ?? "—")}{column === "percentage" ? "%" : ""}</td>)}</tr>)}</tbody></table></div> : <Empty text="No campaign data for this period."/>}</article>; }
