"use client";

import { useEffect, useState } from "react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { Empty, Loading, RangeSelect } from "@/components/dashboard-overview";

export type ReportRow = { [key: string]: string | number | null };
const colors = ["#062f5f", "#2563eb", "#60a5fa", "#f4b41a", "#16a34a", "#9333ea", "#64748b"];

export default function AnalyticsDashboard() {
  const [range, setRange] = useState("30d");
  const [sources, setSources] = useState<ReportRow[]>([]);
  const [campaigns, setCampaigns] = useState<ReportRow[]>([]);
  const [pages, setPages] = useState<ReportRow[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); Promise.all(["sources", "campaigns", "pages"].map((endpoint) => fetch(`/api/analytics/${endpoint}?range=${range}`).then((response) => response.json()))).then(([sourceBody, campaignBody, pageBody]) => { setSources(sourceBody.data ?? []); setCampaigns(campaignBody.data ?? []); setPages(pageBody.data ?? []); }).finally(() => setLoading(false)); }, [range]);
  const campaignVisitors = campaigns.reduce((sum, row) => sum + Number(row.visitors ?? 0), 0);
  const campaignConversions = campaigns.reduce((sum, row) => sum + Number(row.conversions ?? 0), 0);
  return <><header className="topbar"><div className="report-intro"><p className="eyebrow">Audience intelligence</p><h1>Website analytics</h1><p className="subtitle">A complete view of acquisition, visitor activity and marketing performance for the selected period.</p></div><RangeSelect value={range} onChange={setRange}/></header>{loading ? <Loading/> : <><section className="insight-grid" aria-label="Analytics highlights"><Insight label="Traffic sources" value={sources.length} note="Distinct ways visitors reached the website"/><Insight label="Tracked campaigns" value={campaigns.length} note={`${campaignVisitors} visitors arrived with campaign tags`}/><Insight label="Campaign enquiries" value={campaignConversions} note="Contact messages attributed to a tagged visit"/></section><div className="analytics-grid"><Distribution title="Traffic sources" note="Unique visitors grouped by how they reached the website" rows={sources} label="source"/><RankedTable title="UTM campaign performance" note="Visitor and enquiry results from tagged marketing links" rows={campaigns} columns={["campaign", "source", "medium", "visitors", "conversions"]}/><RankedTable title="Most viewed pages" note="Page activity during the selected reporting period" rows={pages} columns={["page", "pageViews", "visitors"]}/><article className="panel"><div className="panel-head"><div><h2>Using campaign tags</h2><p className="panel-note">UTMs make marketing performance visible.</p></div></div><div className="campaign-guidance"><p>Add UTM parameters to a link shared in an advert, email, social post or partner campaign. When someone follows it, this report records the source, medium and campaign name alongside their visit.</p><code>?utm_source=linkedin&amp;utm_medium=organic&amp;utm_campaign=leadership-forum</code></div></article></div></>}</>;
}

function Insight({ label, value, note }: { label: string; value: string | number; note: string }) { return <article className="insight-card"><p>{label}</p><strong>{value}</strong><span>{note}</span></article>; }
export function Distribution({ title, note, rows, label }: { title: string; note: string; rows: ReportRow[]; label: string }) { const chartData = rows.map((row) => ({ name: String(row[label]), value: Number(row.visitors) })); return <article className="panel"><div className="panel-head"><div><h2>{title}</h2><p className="panel-note">{note}</p></div></div>{rows.length ? <div className="distribution"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="value" nameKey="name" innerRadius={56} outerRadius={82} paddingAngle={2}>{chartData.map((_, index) => <Cell key={index} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="legend">{rows.slice(0, 7).map((row, index) => <div key={String(row[label])}><span style={{ background: colors[index % colors.length] }}/><strong>{String(row[label])}</strong><em>{String(row.percentage)}%</em></div>)}</div></div> : <Empty text="No data for this period."/>}</article>; }
export function RankedTable({ title, note = "Based on the selected reporting period", rows, columns, emptyText = "No data for this period." }: { title: string; note?: string; rows: ReportRow[]; columns: string[]; emptyText?: string }) { return <article className="panel"><div className="panel-head"><div><h2>{title}</h2><p className="panel-note">{note}</p></div></div>{rows.length ? <div className="table-scroll compact"><table><thead><tr>{columns.map((column) => <th key={column}>{column.replace(/([A-Z])/g, " $1")}</th>)}</tr></thead><tbody>{rows.slice(0, 10).map((row, index) => <tr key={index}>{columns.map((column) => <td key={column}>{String(row[column] ?? "—")}{column === "percentage" ? "%" : ""}</td>)}</tr>)}</tbody></table></div> : <Empty text={emptyText}/>}</article>; }
