"use client";

import { LoaderCircle, Trash2, X } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";

type User = { id: string; name: string; email: string; role: string; active: boolean; mustChangePassword: boolean; lastLoginAt?: string };

export default function UsersManager() {
  const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [creating, setCreating] = useState(false); const [pendingDelete, setPendingDelete] = useState<User | null>(null); const [deleting, setDeleting] = useState(false);
  async function load() { const body = await fetch("/api/admin/users").then((response) => response.json()); setUsers(body.data ?? []); }
  useEffect(() => { load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setNotice(""); setCreating(true); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), password: form.get("password"), role: form.get("role") }) }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? "Could not create administrator."); return; } event.currentTarget.reset(); setNotice("Administrator created. They can sign in and go directly to the overview."); await load(); } finally { setCreating(false); } }
  async function confirmDelete() { if (!pendingDelete) return; setDeleting(true); setError(""); try { const response = await fetch(`/api/admin/users/${pendingDelete.id}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? "Could not delete administrator."); return; } setNotice(body.data.message); setPendingDelete(null); await load(); } finally { setDeleting(false); } }
  return <><header className="topbar"><div><p className="eyebrow">Access management</p><h1>Administrators</h1><p className="subtitle">Manage the people permitted to access private website data.</p></div></header>{error && <p className="notice error" role="alert">{error}</p>}{notice && <p className="notice success">{notice}</p>}<div className="split-grid"><section className="panel"><div className="panel-head"><div><h2>Current administrators</h2><p className="panel-note">Owner and delegated admin accounts</p></div></div><div className="user-list">{users.map((user) => <div className="user-row" key={user.id}><div className="sender-avatar">{user.name.charAt(0)}</div><div><strong>{user.name}</strong><span>{user.email}</span></div><div className="user-actions"><span className="role-chip">{user.role}</span><small>{user.lastLoginAt ? `Last login ${new Date(user.lastLoginAt).toLocaleDateString("en-GB")}` : "Never signed in"}</small><button className="danger-button" type="button" onClick={() => setPendingDelete(user)}><Trash2 size={14}/> Delete</button></div></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Add administrator</h2><p className="panel-note">Create an account with a secure password</p></div></div><form className="auth-form compact-form" onSubmit={submit}><label>Full name<input name="name" required disabled={creating}/></label><label>Email address<input name="email" type="email" required disabled={creating}/></label><label>Password<input name="password" type="password" minLength={12} required disabled={creating}/></label><label>Role<select name="role" defaultValue="ADMIN" disabled={creating}><option value="ADMIN">Administrator</option><option value="OWNER">Owner</option></select></label><button type="submit" disabled={creating}>{creating ? <><LoaderCircle className="button-spinner" size={17}/> Creating administrator…</> : "Create administrator"}</button></form></section></div>{pendingDelete && <div className="modal-backdrop" role="presentation"><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-admin-title"><button className="icon-button dialog-close" type="button" onClick={() => setPendingDelete(null)} aria-label="Cancel deletion" disabled={deleting}><X size={18}/></button><p className="eyebrow">Permanent action</p><h2 id="delete-admin-title">Delete {pendingDelete.name}?</h2><p>This permanently removes their administrator account and ends their active sessions. This cannot be undone.</p><div className="dialog-actions"><button className="secondary-button" type="button" onClick={() => setPendingDelete(null)} disabled={deleting}>Cancel</button><button className="danger-button solid" type="button" onClick={confirmDelete} disabled={deleting}>{deleting ? <><LoaderCircle className="button-spinner" size={16}/> Deleting…</> : "Delete account"}</button></div></section></div>}</>;
}
